In [1]:
import numpy as np

In [5]:
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],
                  [2,3,4]])
array3 = np.array([[[1,2,3]]])
print(array1,type(array1),array1.shape)
print(array2,type(array2),array2.shape)
print(array3,type(array3),array3.shape)

[1 2 3] <class 'numpy.ndarray'> (3,)
[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3)
[[[1 2 3]]] <class 'numpy.ndarray'> (1, 1, 3)


In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float.dtype)
# 그 반대의 경우
array_int2 = array_float.astype('int32')
print(array_int2.dtype)

float64
int32


In [10]:
zero_array = np.zeros((3,2),dtype='int')
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [11]:
one_array = np.ones((3,2))
print(one_array, one_array.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64


In [12]:
#reshape
ar1 = np.arange(10)
print(ar1,ar1.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [15]:
ar2 = np.arange(10).reshape(2,5)


In [ ]:
ar3 = np.arrange(10).

In [ ]:
# reshape,-1

In [ ]:
ar1 = np.arange(10)
print(ar1,ar1.shape)
print(ar1.reshape(2,-1))
print(ar1.reshape(-1,2,5))


In [ ]:
# 3차원 >>1,2차원
ar3 = np.arange(8),reshape((2,2,2))
ar3 

In [ ]:
ar3 = np.arange(8).reshape((2,2,2))
ar2 = ar3.reshape(-1,2)
ar1 = ar3.reshape(-1,)
print(ar3, ar3.shape)
print(ar2, ar2.shape)
print(ar1, ar1.shape)


In [22]:
# indexing
ar1 = np.arange(1,10)
print(ar1)
value = ar1[1]
print(value)
print(ar1[-1])
print(ar1[-3])

[1 2 3 4 5 6 7 8 9]
2
9
7


In [24]:
ar2d = np.arange(1,10).reshape(3,3)
print(ar2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(ar2d[0,0])
print(ar2d[0,1])
print(ar2d[1,0])
print(ar2d[2,2])

1
2
4
9


In [26]:
#slicing
ar1 = np.arange(1,20)
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [28]:
arr1 = ar1[3:6]
arr2 = ar1[-4:-1]
print(arr1)
print(arr2)

[4 5 6]
[16 17 18]


In [29]:
ar2d = np.arange(1,10).reshape(3,3)
print(ar2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print(ar2d[:2,:2])

[[1 2]
 [4 5]]


In [33]:
print(ar2d[1:3,0:3])
print(ar2d[1:3,:])

[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [34]:
print(ar2d[:2,1:])

[[2 3]
 [5 6]]


In [35]:
print(ar2d[:2,0])


[1 4]


In [40]:
# fancy indexing
ar2 = np.arange(1,10).reshape(3,3)
print(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
print(ar2[[0,1],2])

[3 6]


In [43]:
print(ar2[[0,1],0:2])

[[1 2]
 [4 5]]


In [44]:
print(ar2[[0,1]])

[[1 2 3]
 [4 5 6]]


In [36]:
# boolean indexing
ar1 = np.arange(1,10)
print(ar1)

[1 2 3 4 5 6 7 8 9]


In [37]:
ar2 = ar1[ar1>5]
print(ar2)

[6 7 8 9]


In [51]:
# 첫번째는 np.sort() : 원본 미반영
ar = np.array([3,1,9,5])
print(ar)
sort_ar = np.sort(ar)
print(sort_ar)
# ndarray.sort() : 원본 반영
print(ar)
sort_ar1 = ar.sort()
print(sort_ar1)
print(ar)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [54]:
# 내림차순 정렬
sort_ar_desc = np.sort(ar)[::-1] # ::은 역순
print(sort_ar_desc)

[9 5 3 1]


In [58]:
# 2차원 이상에서 정렬하는방법
ar2 = np.array([[8,12],
                [7,1]])
print(ar2)
sort_ar2_axis0 = np.sort(ar2,axis=0)
print(sort_ar2_axis0)
sort_ar1_axis1 = np.sort(ar2,axis=1)
print(sort_ar1_axis1)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [61]:
# 정렬 행렬의 인덱스 반환
ar = np.array([3,1,9,5])
print(ar)
sort_indices = np.argsort(ar)
print(sort_indices) # 3,1,9,5의 순서를 나타내기 1은1번째,3은 2번째

[3 1 9 5]
[1 0 3 2]


In [64]:
# 행렬내적
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[7,8],
             [9,10],
             [11,12]])

In [65]:
 np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [68]:
# 전치행렬
a = np.array([[1,2],
             [3,4]])

In [69]:
ap = np.transpose(a)
a.T

array([[1, 3],
       [2, 4]])